### ISSUE TITLE
merge main.sh, append.sh, and lib.sh?

### ISSUE THREAD

**Issue by ajashton** [mapbox/dynamosm-importer#45]
There's a bunch of similar logic duplicated across these files, and they're all pretty short scripts. They could reasonably be merged into 1 file with create/append mode determined by a command line option.

**Comment by ian29** [comment]
@ajashton i was able so get consolidate these 3 files into 1 file, but ran into bashquotesadness when trying to abstract out some of the create/append logic. basically you want logic like this 

```sh
if [[ "$mode" == "create" ]]; then
  cmd="parallel --round-robin \"/path/to/import.js 'query'\""
elif [[ "$mode" == "append" ]]; then
  cmd="/path/to/import.js \"query\""
fi
```

or so, except with bash quotes that work for create mode. the hard part is passing in a command to `parallel` where the argument of that command needs to be a string that has spaces in it, aka the query arg. maybe you have better ideas than i did this afternoon?

**Comment by ajashton** [comment]
:eyes: looking

**Comment by ian29** [comment]
this happened.
